### ISSUE TITLE
wrong date format in order overview

### ISSUE THREAD

**Issue by hw-dwalter** [robjuz/futtertrog#33]
![image](https://user-images.githubusercontent.com/1303452/51737453-e9b56400-208c-11e9-9ffc-1d1f60639957.png)

**Comment by robjuz** [comment]
@hw-dwalter What is the correct german date format?
8 Februar 2019 ?
08.02.2019 ?

**Comment by hw-dwalter** [comment]
both are correct. last one is preferred. only the leading zero was missing.
